### ISSUE TITLE
Errors even if it is successful

### ISSUE THREAD

**Issue by nahtnam** [fregante/web-ext-submit#1]
Hey,

I am using this package to publish to the AMO but the command keeps erroring. However, after a few minutes I get a success message from Firefox saying that the new version has been published.

I have the two environment variables set, and have the extension ID set in my manifest.json: https://github.com/ludicrousxyz/tab/blob/develop/public/manifest.json

Any idea what is going on? Here is the output.
```
➜  dist git:(develop) ✗ ../node_modules/.bin/web-ext-submit
Building web extension from /Users/nahtnam/Desktop/..../dist
Validating add-on [............................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/214b4de0cdae4e80bf172d7aabe7b532
0
FAIL

WebExtError: The extension could not be signed
    at _callee$ (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:137:15)
    at tryCatch (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Thanks!

**Comment by fregante** [comment]
That appears to be an issue with the validation, rather than this module, as shown in the link: https://addons.mozilla.org/en-US/developers/upload/214b4de0cdae4e80bf172d7aabe7b532

Try `web-ext sign` (https://github.com/mozilla/web-ext) and see what the output of that is.

The scope of this wrapper is to just avoid the unnecessary error received because of the delayed signing (which happens after a few minutes instead of instantly) but other errors are let through

**Comment by nahtnam** [comment]
Here is the output from the regular sign:

```
Building web extension from /Users/nahtnam/Desktop/.../dist
Validating add-on [....................................................................................................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/d231289af4a042d59c33bddd34b2aa4d
Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
FAIL

WebExtError: The extension could not be signed
    at _callee$ (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:137:15)
    at tryCatch (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/nahtnam/.nvm/versions/node/v10.14.2/lib/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

While I agree, it is erroring, the validation has technically passed since they are only warnings and not an error. I do indeed get the email after a few minutes saying everything is okay and the extension has been released to the public. Is this out of the scope of this project? I feel like since it passes validation and fails on the signing part, it should be covered on this package.

**Comment by fregante** [comment]
> While I agree, it is erroring, the validation has technically passed since they are only warnings and not an error. I do indeed get the email after a few minutes saying everything is okay and the extension has been released to the public

That's exactly the scope of this project: to avoid that specific error. It's strange because it's been working well for extensions. For example this one published yesterday: https://travis-ci.org/sindresorhus/refined-github/builds/468458716 (open the "Deploying application" group at the very bottom)

Are you running it locally? macOS?

**Comment by nahtnam** [comment]
Weird, it looks like my email response didn't register here. 

Yes, I am currently running this locally on macOS (latest) and I verified I have all three commands installed. I used that repository as well to help set this up so I don't know why it's not working. 

Thanks!

**Comment by fregante** [comment]
I think this only works on Linux, maybe `sed` or `tee` work slightly differently on macOS. Locally you can just use the regular `web-ext sign` and ignore the exit code
